import type { PolicyEdition } from '../policyContent'

export default {
  title: 'AI Risk Disclosure Framework',
  lastUpdated: 'July 15, 2026',
  effectiveDate: 'June 1, 2026',
  callout: [
    "Dutiva uses artificial intelligence to power the Dutiva Advisor and document generation features. This framework discloses the risks associated with AI-generated outputs, explains the limitations of the technology, identifies scenarios where human professional review is required, and describes the responsibilities of users who rely on Dutiva's AI features.",
  ],
  sections: [
    {
      title: '1. Accuracy Limitations',
      blocks: [
        {
          type: 'p',
          text: "AI language models generate outputs based on statistical patterns in training data and retrieved context. This means Dutiva's AI outputs may be factually incorrect, incomplete, internally inconsistent, or unsuitable for a specific workplace situation even when they appear confident and well-formatted.",
        },
        {
          type: 'p',
          text: "Dutiva's AI features are grounded with retrieved guidance from Canadian employment standards and HR compliance sources, which reduces but does not eliminate the risk of inaccurate outputs. Users must verify all AI-generated content before relying on it.",
        },
      ],
    },
    {
      title: '2. Hallucination Risk',
      blocks: [
        {
          type: 'p',
          text: "AI language models can 'hallucinate' — generating plausible-sounding but factually incorrect information, including citations to laws or cases that do not exist, incorrect statutory thresholds, or fabricated policy references.",
        },
        {
          type: 'p',
          text: 'Before relying on any legal reference, statutory citation, or numerical threshold generated by Dutiva Advisor or the document generator, verify it against the primary source. Do not assume a citation is accurate because it appears in a well-formatted response.',
        },
      ],
    },
    {
      title: '3. Bias and Fairness',
      blocks: [
        {
          type: 'p',
          text: 'AI models can reflect biases present in training data, which may result in outputs that contain unintended assumptions about employees, workplace roles, gender, age, disability status, or other characteristics. Dutiva reviews template outputs and guidance content for bias, but cannot guarantee that all outputs are free from bias.',
        },
        {
          type: 'p',
          text: 'Users are responsible for reviewing all generated documents for discriminatory language or assumptions before use. Documents used to make employment decisions must comply with applicable human rights legislation regardless of how they were generated.',
        },
      ],
    },
    {
      title: '4. Outdated Information',
      blocks: [
        {
          type: 'p',
          text: 'Employment standards, privacy law, and HR compliance requirements change over time. AI training data has a knowledge cutoff date, and even retrieved guidance content may not reflect the most recent legislative amendments, regulatory guidance, or court decisions.',
        },
        {
          type: 'p',
          text: "Dutiva updates its guidance content on a rolling basis but cannot guarantee that all content reflects the current state of the law at all times. For matters involving recent legislative changes, check the primary source before relying on Dutiva's output.",
        },
      ],
    },
    {
      title: '5. Scenarios Requiring Human Professional Review',
      blocks: [
        {
          type: 'p',
          text: 'AI-generated outputs should not be used as the final decision-maker for any of the following scenarios without qualified human professional review:',
        },
        {
          type: 'li',
          text: 'Terminations, layoffs, or constructive dismissal situations, particularly where there is severance risk, litigation risk, or a human rights component.',
        },
        {
          type: 'li',
          text: 'Accommodation requests involving disability, religion, pregnancy, family status, or any other protected ground under human rights legislation.',
        },
        {
          type: 'li',
          text: 'Workplace investigations involving harassment, violence, discrimination, or reprisal allegations.',
        },
        {
          type: 'li',
          text: 'Situations involving unionized employees or employees in the process of organizing.',
        },
        {
          type: 'li',
          text: 'Privacy incidents, data breaches, or employee monitoring programs.',
        },
        {
          type: 'li',
          text: 'Executive employment agreements, equity compensation, or high-dollar severance arrangements.',
        },
        {
          type: 'li',
          text: 'Any matter where a formal legal demand, grievance, tribunal proceeding, or litigation has been initiated or is threatened.',
        },
        {
          type: 'li',
          text: 'Cross-border or multi-jurisdiction employment situations.',
        },
      ],
    },
    {
      title: '6. User Responsibilities',
      blocks: [
        {
          type: 'p',
          text: "By using Dutiva's AI features, you acknowledge that: (1) AI outputs are drafting aids, not legal advice; (2) you are responsible for reviewing and verifying all outputs before use; (3) you will not rely on AI outputs as a substitute for qualified professional advice in high-risk situations; and (4) you accept responsibility for any workplace decisions you make using Dutiva outputs.",
        },
        {
          type: 'p',
          text: 'If an Advisor response appears incorrect, outdated, or potentially harmful, do not rely on it. Report the issue to support@dutiva.ca with details of the question and response so we can investigate and update our guidance content.',
        },
      ],
    },
    {
      title: '7. Ongoing Improvements',
      blocks: [
        {
          type: 'p',
          text: 'Dutiva continuously works to improve the accuracy, relevance, and safety of its AI outputs through guidance content updates, model evaluation, prompt engineering, retrieval improvements, and user feedback review. We do not guarantee that improvements will eliminate all risks described in this framework.',
        },
        {
          type: 'p',
          text: 'For questions about AI risk or to report a harmful output, contact support@dutiva.ca.',
        },
      ],
    },
  ],
} satisfies PolicyEdition
