import { DOC_DISCLAIMER_NOTE } from './data/meta'
import type { DocTemplate } from './data/types'

/**
 * Hand-authored doclib templates — deliberately NOT under data/templates/.
 * That folder was machine-generated by scripts/generate-doclib.mjs, which
 * would have clobbered anything added there on a regen. (That generator has
 * since been retired as unrunnable, so data/templates/ now also accepts
 * authored templates — numbered from T21 up, because the tids below are
 * live: doclib wins the `templateByTid ?? customTemplateByTid` lookup, so a
 * reused tid shadows these silently rather than colliding.) These four port
 * the
 * content of legacy docstudio-only templates (src/data/documents.ts) that
 * are actually referenced from employee/case fixtures but have no doclib
 * counterpart, so the docstudio overlay can resolve them via the doclib
 * data model instead of the flat legacy shape.
 *
 * Content (jurisdiction notes, statutory references, clause text) is
 * carried forward from the legacy fixture's existing `meta`/`sections`
 * fields, not invented. `bodyHtmlEn` is intentionally omitted — the
 * overlay adapter and the wizard preview both read `preview` blocks, and
 * inventing a full formatted letter body not present in the source would
 * cross from porting into drafting new legal language.
 *
 * Accommodation Documentation (T19) and Medical Information Request
 * Letter (T20) now sit in the `accommodation` category rather than
 * `discipline`, which is where the legacy fixture had put them: filing an
 * accommodation record under discipline misstates what the document is, and
 * the two belong beside the rest of the process (T21–T24). They were
 * British Columbia content in the legacy fixture, but
 * doclib's `Jurisdiction` type only models 'ON' | 'QC' | 'FED' and this
 * pass is scoped to those three only — no other jurisdiction yet. Both
 * were rewritten for ON/QC/FED coverage instead of carrying the BC text
 * forward: the underlying duty to accommodate to the point of undue
 * hardship is common to Ontario's Human Rights Code, Quebec's Charte des
 * droits et libertés de la personne, and the Canadian Human Rights Act
 * (federally regulated employers) alike, so this is the same well-settled
 * principle the rest of the app already cites (see e.g. T03's ESA/Canada
 * Labour Code/Civil Code split), not new legal territory.
 */

export const tplT17: DocTemplate = {
  id: 'tpl_t17',
  tid: 'T17',
  key: 'full_final_release',
  kind: 'agreement',
  category: 'termination',
  core: false,
  name: { en: 'Full & final release', fr: 'Quittance complète et finale' },
  desc: {
    en: 'Release of claims provided in exchange for enhanced termination payment. Requires independent legal advice for the employee before signing.',
    fr: 'Quittance de réclamations fournie en échange d’une indemnité de cessation bonifiée. Nécessite un avis juridique indépendant pour l’employé avant la signature.',
  },
  jurisdictions: ['ON'],
  risk: 'high',
  review: 'lawyer_review_recommended',
  requiresLawyerReview: true,
  version: 'v1',
  versionNumber: 1,
  effectiveDate: '2026-07-14',
  updatedAt: '2026-07-14',
  estMinutes: 8,
  usageCount: 0,
  statutory: [
    {
      en: 'ESA, 2000 — statutory rights cannot be waived',
      fr: 'LNE, 2000 — les droits légaux ne peuvent être levés',
    },
  ],
  jurisdictionNotes: {
    ON: {
      en: 'A release cannot waive rights that cannot be waived by law, including certain human rights or workers’ compensation claims. Consideration above the statutory minimum is what supports the release.',
      fr: 'Une quittance ne peut lever des droits qui ne peuvent être levés par la loi, y compris certaines réclamations relatives aux droits de la personne ou à l’indemnisation des accidents du travail. Une contrepartie supérieure au minimum légal appuie la quittance.',
    },
  },
  includes: [
    { en: 'Consideration (enhanced payment)', fr: 'Contrepartie (indemnité bonifiée)' },
    { en: 'Scope of release', fr: 'Portée de la quittance' },
    {
      en: 'Non-waivable claims carve-out',
      fr: 'Exclusion des réclamations non susceptibles de renonciation',
    },
    {
      en: 'Independent legal advice acknowledgment',
      fr: 'Attestation de conseil juridique indépendant',
    },
  ],
  questions: [
    {
      id: 'employee_name',
      section: { en: 'Employee', fr: 'Employé' },
      label: { en: 'Employee full name', fr: 'Nom complet de l’employé(e)' },
      type: 'text',
      required: true,
    },
    {
      id: 'effective_date',
      section: { en: 'Timing', fr: 'Échéancier' },
      label: { en: 'Termination effective date', fr: 'Date d’effet de la cessation' },
      type: 'date',
      required: true,
    },
  ],
  preview: [
    { type: 'title', text: { en: 'Release of Claims', fr: 'Quittance de réclamations' } },
    {
      type: 'meta',
      text: {
        en: '{{org}} · {{today}} · {{jurisdiction}}',
        fr: '{{org}} · {{today}} · {{jurisdiction}}',
      },
    },
    {
      type: 'para',
      text: {
        en: 'In exchange for the enhanced payment described in the accompanying termination letter, {{employee_name}} agrees to release {{org}} from all claims arising from their employment or its end, effective {{effective_date}}, to the extent permitted by law.',
        fr: 'En échange du paiement bonifié décrit dans la lettre de cessation d’emploi ci-jointe, {{employee_name}} accepte de libérer {{org}} de toute réclamation découlant de son emploi ou de sa fin, en date du {{effective_date}}, dans la mesure permise par la loi.',
      },
    },
    {
      type: 'clause',
      n: 1,
      heading: {
        en: 'Claims that cannot be released',
        fr: 'Réclamations ne pouvant faire l’objet d’une quittance',
      },
      text: {
        en: 'This release does not affect any claim that cannot be waived by law, including certain human rights or workers’ compensation claims.',
        fr: 'Cette quittance n’affecte aucune réclamation qui ne peut être levée par la loi, y compris certaines réclamations relatives aux droits de la personne ou à l’indemnisation des accidents du travail.',
      },
    },
    {
      type: 'clause',
      n: 2,
      heading: { en: 'Independent legal advice', fr: 'Conseil juridique indépendant' },
      text: {
        en: 'The employee should obtain independent legal advice before signing. A standard acknowledgement clause confirming this is included below.',
        fr: 'L’employé devrait obtenir un avis juridique indépendant avant de signer. Une clause de reconnaissance standard confirmant cela est incluse ci-dessous.',
      },
    },
    {
      type: 'sig',
      roles: [
        { en: 'Employer representative', fr: 'Représentant de l’employeur' },
        { en: 'Employee', fr: 'Employé(e)' },
      ],
    },
    {
      type: 'note',
      tone: 'risk',
      text: {
        en: 'Higher-risk document. Lawyer review is recommended before this is sent or signed.',
        fr: 'Document à risque élevé. Une révision juridique est recommandée avant l’envoi ou la signature.',
      },
    },
    {
      type: 'note',
      tone: 'info',
      text: DOC_DISCLAIMER_NOTE,
    },
  ],
  subject: 'employee',
}

export const tplT18: DocTemplate = {
  id: 'tpl_t18',
  tid: 'T18',
  key: 'offboarding_checklist',
  kind: 'checklist',
  category: 'termination',
  core: false,
  name: { en: 'Offboarding checklist', fr: 'Liste de vérification de départ' },
  desc: {
    en: 'Final-pay, benefits, equipment, and ROE checklist for an employee’s last day.',
    fr: 'Liste de vérification pour la paie finale, les avantages, l’équipement et le RE au dernier jour d’un employé.',
  },
  jurisdictions: ['ON'],
  risk: 'low',
  review: 'hr_review_required',
  requiresLawyerReview: false,
  version: 'v1',
  versionNumber: 1,
  effectiveDate: '2026-07-14',
  updatedAt: '2026-07-14',
  estMinutes: 5,
  usageCount: 0,
  statutory: [
    { en: 'ESA, 2000 — Record of Employment timing', fr: 'LNE, 2000 — délai du relevé d’emploi' },
  ],
  jurisdictionNotes: {
    ON: {
      en: 'Record of Employment must be issued within 5 calendar days of the interruption of earnings.',
      fr: 'Le relevé d’emploi doit être émis dans les 5 jours civils suivant l’interruption de la rémunération.',
    },
  },
  includes: [
    { en: 'Final pay & accrued vacation', fr: 'Paie finale et vacances accumulées' },
    { en: 'Benefits end date', fr: 'Date de fin des avantages' },
    { en: 'Equipment & access revocation', fr: 'Révocation de l’équipement et des accès' },
    { en: 'Record of Employment', fr: 'Relevé d’emploi' },
    { en: 'Exit interview', fr: 'Entrevue de départ' },
  ],
  questions: [
    {
      id: 'employee_name',
      section: { en: 'Employee', fr: 'Employé' },
      label: { en: 'Employee full name', fr: 'Nom complet de l’employé(e)' },
      type: 'text',
      required: true,
    },
    {
      id: 'last_day',
      section: { en: 'Timing', fr: 'Échéancier' },
      label: { en: 'Last day worked', fr: 'Dernier jour travaillé' },
      type: 'date',
      required: true,
    },
  ],
  preview: [
    { type: 'title', text: { en: 'Offboarding Checklist', fr: 'Liste de vérification de départ' } },
    {
      type: 'meta',
      text: {
        en: '{{employee_name}} · last day {{last_day}}',
        fr: '{{employee_name}} · dernier jour {{last_day}}',
      },
    },
    {
      type: 'para',
      text: {
        en: 'Final pay and accrued vacation calculated and scheduled.',
        fr: 'Paie finale et vacances accumulées calculées et planifiées.',
      },
    },
    {
      type: 'para',
      text: {
        en: 'Benefits end date confirmed with the provider.',
        fr: 'Date de fin des avantages confirmée avec le fournisseur.',
      },
    },
    {
      type: 'para',
      text: {
        en: 'Company equipment and access revoked on the last day.',
        fr: 'Équipement et accès de l’entreprise révoqués le dernier jour.',
      },
    },
    {
      type: 'para',
      text: {
        en: 'Record of Employment (ROE) issued within 5 calendar days.',
        fr: 'Relevé d’emploi (RE) émis dans les 5 jours civils.',
      },
    },
    {
      type: 'para',
      text: {
        en: 'Exit interview scheduled; reference contact designated.',
        fr: 'Entrevue de départ planifiée ; personne-ressource de référence désignée.',
      },
    },
    /* Added when the disclaimer guard was extended to the whole catalogue: this
       was the one shipped template carrying no disclaimer at all. */
    {
      type: 'note',
      tone: 'info',
      text: DOC_DISCLAIMER_NOTE,
    },
  ],
  subject: 'employee',
}

export const tplT19: DocTemplate = {
  id: 'tpl_t19',
  tid: 'T19',
  key: 'accommodation_documentation',
  kind: 'record',
  category: 'accommodation',
  core: false,
  name: { en: 'Accommodation documentation', fr: 'Documentation d’accommodement' },
  desc: {
    en: 'Confidential record of functional limitations and the accommodation plan — no diagnosis on file.',
    fr: 'Dossier confidentiel des limitations fonctionnelles et du plan d’accommodement — aucun diagnostic au dossier.',
  },
  jurisdictions: ['ON', 'QC', 'FED'],
  risk: 'high',
  review: 'lawyer_review_recommended',
  requiresLawyerReview: true,
  version: 'v1',
  versionNumber: 1,
  effectiveDate: '2026-07-14',
  updatedAt: '2026-07-14',
  estMinutes: 8,
  usageCount: 0,
  statutory: [
    {
      en: 'Human Rights Code (Ontario) — duty to accommodate to the point of undue hardship',
      fr: 'Code des droits de la personne (Ontario) — obligation d’accommodement jusqu’au point de préjudice injustifié',
    },
    {
      en: 'Charte des droits et libertés de la personne (Quebec), art. 10',
      fr: 'Charte des droits et libertés de la personne (Québec), art. 10',
    },
    {
      en: 'Canadian Human Rights Act — federally regulated employers',
      fr: 'Loi canadienne sur les droits de la personne — employeurs sous réglementation fédérale',
    },
  ],
  jurisdictionNotes: {
    ON: {
      en: 'Human Rights Code duty to accommodate to the point of undue hardship. Medical information must be limited to functional limitations, not diagnosis.',
      fr: 'Obligation d’accommodement du Code des droits de la personne jusqu’au point de préjudice injustifié. Les renseignements médicaux doivent se limiter aux limitations fonctionnelles, sans diagnostic.',
    },
    QC: {
      en: 'Charte art. 10 prohibits discrimination based on disability; the same duty to accommodate to the point of undue hardship applies. Diagnosis-level medical detail is not required.',
      fr: 'L’art. 10 de la Charte interdit la discrimination fondée sur le handicap ; la même obligation d’accommodement jusqu’au point de préjudice injustifié s’applique. Un diagnostic n’est pas requis.',
    },
    FED: {
      en: 'Canadian Human Rights Act duty to accommodate applies to federally regulated employers, with the same undue-hardship threshold and functional-limitations-only scope.',
      fr: 'L’obligation d’accommodement de la Loi canadienne sur les droits de la personne s’applique aux employeurs sous réglementation fédérale, avec le même seuil de préjudice injustifié et la même portée limitée aux limitations fonctionnelles.',
    },
  },
  includes: [
    {
      en: 'Functional limitations (not diagnosis)',
      fr: 'Limitations fonctionnelles (sans diagnostic)',
    },
    { en: 'Accommodation plan', fr: 'Plan d’accommodement' },
    { en: 'Next review date', fr: 'Prochaine date d’examen' },
  ],
  questions: [
    {
      id: 'employee_name',
      section: { en: 'Employee', fr: 'Employé' },
      label: { en: 'Employee full name', fr: 'Nom complet de l’employé(e)' },
      type: 'text',
      required: true,
    },
    {
      id: 'review_date',
      section: { en: 'Timing', fr: 'Échéancier' },
      label: {
        en: 'Next accommodation review date',
        fr: 'Prochaine date d’examen de l’accommodement',
      },
      type: 'date',
      required: true,
    },
  ],
  preview: [
    {
      type: 'title',
      text: {
        en: 'Accommodation Record — Confidential',
        fr: 'Dossier d’accommodement — Confidentiel',
      },
    },
    {
      type: 'meta',
      text: { en: '{{employee_name}} · {{today}}', fr: '{{employee_name}} · {{today}}' },
    },
    {
      type: 'para',
      text: {
        en: 'Modified duties are in place based on documented functional limitations. The file holds functional limitations only — no diagnosis — consistent with human rights obligations.',
        fr: 'Des tâches modifiées sont en place selon des limitations fonctionnelles documentées. Le dossier ne contient que les limitations fonctionnelles — aucun diagnostic — conformément aux obligations en matière de droits de la personne.',
      },
    },
    {
      type: 'clause',
      n: 1,
      heading: { en: 'Accommodation plan', fr: 'Plan d’accommodement' },
      text: {
        en: 'Modified duties reviewed every 90 days or as functional limitations change. Next review: {{review_date}}.',
        fr: 'Tâches modifiées révisées tous les 90 jours ou lorsque les limitations fonctionnelles changent. Prochain examen : {{review_date}}.',
      },
    },
    {
      type: 'note',
      tone: 'risk',
      text: {
        en: 'Higher-risk, privacy-sensitive document. Lawyer review is recommended before this is placed on file.',
        fr: 'Document à risque élevé et de nature confidentielle. Une révision juridique est recommandée avant de le verser au dossier.',
      },
    },
    {
      type: 'note',
      tone: 'info',
      text: DOC_DISCLAIMER_NOTE,
    },
  ],
  subject: 'employee',
}

export const tplT20: DocTemplate = {
  id: 'tpl_t20',
  tid: 'T20',
  key: 'medical_information_request_letter',
  kind: 'letter',
  category: 'accommodation',
  core: false,
  name: {
    en: 'Medical information request letter',
    fr: 'Lettre de demande de renseignements médicaux',
  },
  desc: {
    en: 'Requests functional-limitation information from a treating provider to support an accommodation — never a diagnosis.',
    fr: 'Demande des renseignements sur les limitations fonctionnelles à un professionnel traitant pour appuyer un accommodement — jamais un diagnostic.',
  },
  jurisdictions: ['ON', 'QC', 'FED'],
  risk: 'high',
  review: 'lawyer_review_recommended',
  requiresLawyerReview: true,
  version: 'v1',
  versionNumber: 1,
  effectiveDate: '2026-07-14',
  updatedAt: '2026-07-14',
  estMinutes: 6,
  usageCount: 0,
  statutory: [
    {
      en: 'Human Rights Code (Ontario) — duty to accommodate to the point of undue hardship',
      fr: 'Code des droits de la personne (Ontario) — obligation d’accommodement jusqu’au point de préjudice injustifié',
    },
    {
      en: 'Charte des droits et libertés de la personne (Quebec), art. 10',
      fr: 'Charte des droits et libertés de la personne (Québec), art. 10',
    },
    {
      en: 'Canadian Human Rights Act — federally regulated employers',
      fr: 'Loi canadienne sur les droits de la personne — employeurs sous réglementation fédérale',
    },
  ],
  jurisdictionNotes: {
    ON: {
      en: 'Requests must be limited to functional limitations and restrictions — diagnosis is not required to support an accommodation under the Human Rights Code.',
      fr: 'Les demandes doivent se limiter aux limitations et restrictions fonctionnelles — un diagnostic n’est pas requis pour appuyer un accommodement en vertu du Code des droits de la personne.',
    },
    QC: {
      en: 'Same functional-limitations-only scope applies under the Charte; medical detail beyond what supports the accommodation should not be requested.',
      fr: 'La même portée limitée aux limitations fonctionnelles s’applique en vertu de la Charte ; aucun renseignement médical au-delà de ce qui appuie l’accommodement ne devrait être demandé.',
    },
    FED: {
      en: 'Federally regulated employers are held to the same functional-limitations standard under the Canadian Human Rights Act.',
      fr: 'Les employeurs sous réglementation fédérale sont tenus à la même norme de limitations fonctionnelles en vertu de la Loi canadienne sur les droits de la personne.',
    },
  },
  includes: [
    {
      en: 'Scope limited to functional limitations',
      fr: 'Portée limitée aux limitations fonctionnelles',
    },
    { en: 'Confidentiality commitment', fr: 'Engagement de confidentialité' },
    { en: 'Reply-by date', fr: 'Date limite de réponse' },
  ],
  questions: [
    {
      id: 'employee_name',
      section: { en: 'Employee', fr: 'Employé' },
      label: { en: 'Employee full name', fr: 'Nom complet de l’employé(e)' },
      type: 'text',
      required: true,
    },
    {
      id: 'provider_name',
      section: { en: 'Provider', fr: 'Professionnel traitant' },
      label: { en: 'Treating provider name', fr: 'Nom du professionnel traitant' },
      type: 'text',
      required: false,
    },
    {
      id: 'reply_by_date',
      section: { en: 'Timing', fr: 'Échéancier' },
      label: { en: 'Reply-by date', fr: 'Date limite de réponse' },
      type: 'date',
      required: true,
    },
  ],
  preview: [
    {
      type: 'title',
      text: {
        en: 'Request for Functional Abilities Information',
        fr: 'Demande de renseignements sur les capacités fonctionnelles',
      },
    },
    {
      type: 'meta',
      text: { en: '{{employee_name}} · {{today}}', fr: '{{employee_name}} · {{today}}' },
    },
    {
      type: 'para',
      text: {
        en: 'To support an appropriate accommodation for {{employee_name}}, we are requesting information from {{provider_name}} limited to functional limitations and restrictions — not diagnosis. Please reply by {{reply_by_date}}.',
        fr: 'Pour soutenir un accommodement approprié pour {{employee_name}}, nous demandons à {{provider_name}} des renseignements limités aux limitations et restrictions fonctionnelles — sans diagnostic. Veuillez répondre d’ici le {{reply_by_date}}.',
      },
    },
    {
      type: 'clause',
      n: 1,
      heading: { en: 'Confidentiality', fr: 'Confidentialité' },
      text: {
        en: 'This information will be kept confidential and used only to determine appropriate workplace accommodation.',
        fr: 'Ces renseignements demeureront confidentiels et ne serviront qu’à déterminer l’accommodement approprié en milieu de travail.',
      },
    },
    {
      type: 'note',
      tone: 'risk',
      text: {
        en: 'Higher-risk, privacy-sensitive document. Lawyer review is recommended before this is sent.',
        fr: 'Document à risque élevé et de nature confidentielle. Une révision juridique est recommandée avant l’envoi.',
      },
    },
    {
      type: 'note',
      tone: 'info',
      text: DOC_DISCLAIMER_NOTE,
    },
  ],
  subject: 'employee',
}

export const customTemplates: DocTemplate[] = [tplT17, tplT18, tplT19, tplT20]
export const customTemplateByTid = new Map(customTemplates.map((t) => [t.tid, t]))
