/*
 *   Copyright (c) 2026
 *   All rights reserved.
 */
/**
 * Build-time generation of the offline service worker (dist/sw.js).
 *
 * Runs at the end of `npm run build`, after the client build, the SSR build,
 * and prerendering — so every hashed asset in dist/assets/, every brand
 * image, and the prerendered shells (/, /app.html, /404.html) already exist
 * and can be precached by exact URL.
 *
 * Why hand-rolled instead of vite-plugin-pwa: this site prerenders a
 * per-route HTML file for SEO and validates it (scripts/validate-seo.mjs),
 * and it runs a separate SSR build. A generate-a-service-worker plugin's
 * default navigation fallback would serve one precached index.html for every
 * route, which fights the prerendered-per-route model. Owning the tiny SW
 * here keeps navigations network-first (online users and crawlers always get
 * fresh, route-specific HTML) while still giving full offline use.
 *
 * Deterministic, like the prerender step: the cache version is a hash of the
 * sorted precache URL list — no build timestamps — so identical output
 * produces an identical sw.js, and any asset change rotates the cache.
 */

import { readdir, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { createHash } from 'node:crypto'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const dist = path.join(root, 'dist')

/** Recursively list files under `dir`, returning paths relative to it. */
async function walk(dir, base) {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const rel = `${base}/${entry.name}`
    if (entry.isDirectory()) out.push(...(await walk(path.join(dir, entry.name), rel)))
    else out.push(rel)
  }
  return out
}

/** All served URLs under a dist subdirectory (e.g. /assets/index-abc123.js). */
async function urlsUnder(subdir, prefix) {
  const abs = path.join(dist, subdir)
  if (!existsSync(abs)) return []
  return (await walk(abs, '')).map((rel) => prefix + rel)
}

const assetUrls = await urlsUnder('assets', '/assets')
const brandUrls = await urlsUnder('brand', '/brand')

/* App shells + manifest. `/` is the prerendered marketing home and doubles as
   the offline fallback for any public route the SPA can re-render client-side;
   `/app.html` is the private workspace shell that Vercel rewrites /app/* to. */
const shell = ['/', '/app.html', '/404.html', '/site.webmanifest'].filter((url) => {
  const file = url === '/' ? 'index.html' : url.replace(/^\//, '')
  return existsSync(path.join(dist, file))
})

/* Never precache source maps: build.sourcemap is 'hidden' and
   relocate-sourcemaps.mjs already moves them out of dist/ before this runs, but
   filter defensively so a stray .map can never end up in the offline cache. */
const precache = Array.from(new Set([...shell, ...assetUrls, ...brandUrls]))
  .filter((url) => !url.endsWith('.map'))
  .sort((a, b) => a.localeCompare(b))

if (assetUrls.length === 0) {
  console.error('generate-sw: no files under dist/assets — did `vite build` run first?')
  process.exit(1)
}

const version = createHash('sha256').update(precache.join('\n')).digest('hex').slice(0, 12)

/* The service-worker body is authored without template literals or `${}` so
   it can be embedded in this generator's template literal without escaping;
   only CACHE_VERSION and PRECACHE_URLS are interpolated. */
const sw = String.raw`/* Generated by scripts/generate-sw.mjs — do not edit by hand.
   Dutiva offline service worker. See docs/OFFLINE_PWA.md. */
const CACHE_VERSION = '${version}'
const PRECACHE = 'dutiva-precache-' + CACHE_VERSION
const RUNTIME = 'dutiva-runtime-' + CACHE_VERSION
const PAGES = 'dutiva-pages-' + CACHE_VERSION
const PRECACHE_URLS = ${JSON.stringify(precache)}

/* Install: fill the precache so a single online visit makes the whole app
   available offline, then take over from any previous worker immediately. */
self.addEventListener('install', function (event) {
  event.waitUntil(
    caches
      .open(PRECACHE)
      .then(function (cache) {
        return cache.addAll(PRECACHE_URLS)
      })
      .then(function () {
        return self.skipWaiting()
      }),
  )
})

/* Activate: drop every cache from a previous version and claim open pages. */
self.addEventListener('activate', function (event) {
  event.waitUntil(
    caches
      .keys()
      .then(function (keys) {
        return Promise.all(
          keys.map(function (key) {
            return key.indexOf(CACHE_VERSION) === -1 ? caches.delete(key) : undefined
          }),
        )
      })
      .then(function () {
        return self.clients.claim()
      }),
  )
})

/* Serve from any cache first (precache included); otherwise fetch and stash a
   copy in the runtime cache. For immutable, content-hashed assets. */
function cacheFirst(request) {
  return caches.match(request).then(function (cached) {
    if (cached) return cached
    return fetch(request).then(function (response) {
      if (response && (response.ok || response.type === 'opaque')) {
        var copy = response.clone()
        caches.open(RUNTIME).then(function (cache) {
          cache.put(request, copy)
        })
      }
      return response
    })
  })
}

/* Which shell to fall back to for an uncached offline navigation: the private
   workspace shell for /app/* and demo subpaths (/demo/home, …), the marketing
   home for everything else. Both boot the SPA, which then renders the requested
   route client-side. */
function shellFor(pathname) {
  if (pathname.indexOf('/app') === 0) return '/app.html'
  if (pathname.startsWith('/demo/') || pathname.startsWith('/fr/demo/')) return '/app.html'
  return '/'
}

/* Network-first so online visitors and crawlers always get fresh, per-route
   prerendered HTML; only fall back to cache — then a shell — when offline. */
function networkFirstPage(request) {
  return fetch(request)
    .then(function (response) {
      if (response && response.ok) {
        var copy = response.clone()
        caches.open(PAGES).then(function (cache) {
          cache.put(request, copy)
        })
      }
      return response
    })
    .catch(function () {
      return caches.match(request).then(function (cached) {
        if (cached) return cached
        var url = new URL(request.url)
        return caches.match(shellFor(url.pathname)).then(function (shell) {
          if (shell) return shell
          return new Response('You are offline.', {
            status: 503,
            headers: { 'Content-Type': 'text/plain; charset=utf-8' },
          })
        })
      })
    })
}

self.addEventListener('fetch', function (event) {
  var request = event.request
  if (request.method !== 'GET') return
  var url = new URL(request.url)

  /* Leave all cross-origin traffic to the network — real backend data
     must never be served stale from a cache. This also covers the client
     error-reporting beacon (a cross-origin POST to the Supabase edge function),
     which is therefore never intercepted or cached; the method guard above
     already excludes it as a non-GET request. Self-hosted fonts ride the
     same-origin hashed assets path below (precache / cache-first). */
  if (url.origin !== self.location.origin) return

  /* Never intercept the worker's own script; the browser revalidates it. */
  if (url.pathname === '/sw.js') return

  if (request.mode === 'navigate') {
    event.respondWith(networkFirstPage(request))
    return
  }

  if (
    url.pathname.indexOf('/assets/') === 0 ||
    url.pathname.indexOf('/brand/') === 0 ||
    /\.(?:js|mjs|css|woff2?|ttf|otf|png|jpe?g|gif|svg|webp|ico|webmanifest)$/.test(url.pathname)
  ) {
    event.respondWith(cacheFirst(request))
  }
})
`

await writeFile(path.join(dist, 'sw.js'), sw)
console.log(`generate-sw: wrote dist/sw.js (${precache.length} precached URLs, version ${version})`)
