-- Full French-body backfill for the advisor grounding corpus.
--
-- Migration 0029 added the title_fr / content_fr / fts_fr columns and
-- backfilled 2 proof-of-concept rows (ON + QC minimum_wage). This migration
-- completes the job for the remaining 40 rows, giving every chunk a French
-- translation so that French-language queries rank against native French
-- prose rather than relying on parenthetical inline terms in the English
-- body.
--
-- Authoring provenance: each French text was authored from the
-- corresponding official French source (CNESST/LNT for QC, Code canadien
-- du travail / Programme du travail for FED, ontario.ca/fr / LNE for ON),
-- following the same standard established in 0029. No content was
-- machine-translated from the English row.
--
-- The fts_fr tsvector column is generated (stored), so it updates
-- automatically when content_fr is set.

-- ===== QUEBEC (12 chunks — minimum_wage already done in 0029) =====

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Québec : obligation d''accommodement raisonnable en vertu de la Charte des droits et libertés de la personne (CDPDJ)',
  content_fr = 'Au Québec, la discrimination et l''accommodement en milieu de travail sont régis par la Charte des droits et libertés de la personne, et non par le droit fédéral des droits de la personne pour les employeurs de compétence provinciale. La Charte interdit la discrimination fondée sur des motifs protégés incluant la race, la couleur, le sexe, l''identité ou l''expression de genre, la grossesse, l''orientation sexuelle, l''état civil, l''âge, la religion, les convictions politiques, la langue, l''origine ethnique ou nationale, la condition sociale et le handicap. Les employeurs ont une obligation d''accommodement raisonnable : ils doivent rechercher activement des solutions — adapter une pratique ou une règle, ou accorder une exemption — pour permettre à une personne confrontée à la discrimination d''exercer pleinement ses droits. Cette obligation s''étend jusqu''à la contrainte excessive : l''accommodement ne peut être refusé que lorsque l''employeur démontre objectivement qu''il imposerait un fardeau financier excessif, entraverait indûment le fonctionnement de l''organisation ou porterait atteinte de façon importante à la sécurité ou aux droits d''autrui. La Commission des droits de la personne et des droits de la jeunesse (CDPDJ) administre la Charte, reçoit les plaintes pour refus d''accommodement et offre des services de formation et de conseil.'
WHERE jurisdiction = 'QC' AND topic = 'accommodation_basics';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Québec — Congédiement déguisé',
  content_fr = 'Les travailleurs du Québec employés par le même employeur depuis au moins 2 ans peuvent déposer une plainte auprès de la CNESST s''ils estiment avoir été congédiés sans une cause juste et suffisante. Le congédiement déguisé en est une forme : un moyen détourné pour l''employeur de congédier un travailleur en présentant la fin de l''emploi comme une mise à pied permanente ou un congédiement ordinaire, ou en imposant des changements importants et injustifiés aux conditions de travail — tels qu''une réduction importante des heures et du taux horaire — qui contraignent effectivement le travailleur à démissionner pour trouver des conditions équivalentes ailleurs. Un concept connexe, la « double sanction », survient lorsqu''un employeur discipline un travailleur deux fois pour le même manquement. Tout changement d''horaire ou de tâches n''est pas un congédiement déguisé : la CNESST donne elle-même l''exemple d''une réduction modeste d''horaire motivée par des raisons d''affaires qui n''a pas été jugée un congédiement déguisé, car les changements n''étaient pas importants. La plainte est entendue par le Tribunal administratif du travail, qui peut ordonner la réintégration, une indemnité pour perte de salaires ou toute autre mesure équitable.'
WHERE jurisdiction = 'QC' AND topic = 'constructive_dismissal';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Québec : semaine normale de travail, heures supplémentaires, périodes de repas, repos hebdomadaire et droit de refus des heures supplémentaires',
  content_fr = 'En vertu de la Loi sur les normes du travail du Québec, la semaine normale de travail est de 40 heures pour la plupart des travailleurs ; les heures au-delà de 40 par semaine sont des heures supplémentaires payées à temps et demi (majorées de 50 % du taux régulier). Certaines catégories ont des semaines normales plus élevées, notamment 44 heures pour les agents de sécurité d''une entreprise de sécurité. Après 5 heures consécutives de travail, l''employeur doit accorder une période de repas non rémunérée de 30 minutes, qui doit être payée si le travailleur ne peut quitter son poste de travail ; les autres pauses ne sont pas obligatoires, mais doivent être payées si elles sont accordées. Les travailleurs ont droit à un repos hebdomadaire d''au moins 32 heures consécutives. Un travailleur peut refuser d''effectuer plus de 2 heures au-delà de ses heures régulières quotidiennes ou plus de 14 heures par période de 24 heures (12 heures pour ceux dont l''horaire est flexible ou non continu), et plus de 50 heures par semaine (60 dans les régions éloignées ou le territoire de la Baie-James). Un travailleur dont le quart de travail est écourté après s''être présenté au travail a généralement droit à 3 heures de salaire.'
WHERE jurisdiction = 'QC' AND topic = 'hours_of_work';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Québec — Mise à pied et règles de rappel',
  content_fr = 'En vertu de la Loi sur les normes du travail du Québec, une mise à pied suspend temporairement le contrat de travail pour des motifs économiques, organisationnels ou techniques ; le lien d''emploi se maintient et le travailleur peut être rappelé. Lors d''une mise à pied prévue de plus de 6 mois, l''employeur doit donner au travailleur un avis de cessation d''emploi écrit dans le délai prévu selon l''ancienneté (1 semaine pour 3 mois à 1 an ; 2 semaines pour 1 à 5 ans ; 4 semaines pour 5 à 10 ans ; 8 semaines pour 10 ans et plus) ; à défaut, le travailleur a droit à une indemnité égale au salaire qu''il aurait gagné pendant la période d''avis manquante. Si une mise à pied est indéterminée ou initialement prévue de moins de 6 mois, mais dépasse cette période, l''employeur doit payer l''indemnité une fois le seuil de 6 mois atteint ; le paiement de cette indemnité ne met pas fin en soi au lien d''emploi. Un travailleur ayant des droits de rappel de plus de 6 mois en vertu d''une convention collective et qui a été mis à pied plus de 6 mois peut réclamer l''indemnité s''il n''est pas rappelé, soit à l''expiration de ses droits de rappel, soit un an après sa mise à pied.'
WHERE jurisdiction = 'QC' AND topic = 'layoffs_recall';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Québec (LNT/CNESST) : congés légaux protégés — maladie, famille/proche aidant, deuil, maternité/paternité/parental',
  content_fr = 'En vertu de la Loi sur les normes du travail du Québec, administrée par la CNESST, un employé peut prendre jusqu''à 26 semaines d''absence protégée sur une période de 12 mois en cas de maladie ou d''accident non lié au travail. Il peut prendre 10 jours par année pour des obligations familiales ou parentales, incluant la garde d''un enfant ou l''assistance à un proche aidant. Les 2 premiers jours par année civile pour ces absences sont payés après 3 mois de service ininterrompu. L''absence prolongée d''aidant est de jusqu''à 16 semaines sur 12 mois pour une maladie ou un accident grave d''un membre de la famille, de 27 semaines si la vie est menacée, et de 36 semaines pour un enfant mineur gravement malade (104 semaines si la maladie de l''enfant met la vie en danger). Le congé de deuil est de 5 jours — 2 payés — pour le conjoint, l''enfant, l''enfant du conjoint, le parent ou le frère ou la sœur, et d''un jour non payé pour certains autres proches. Le congé de maternité est de 18 semaines consécutives, le congé de paternité de 5 semaines et le congé parental jusqu''à 65 semaines, tous non payés ; les prestations de revenus sont distinctes et versées par le Régime québécois d''assurance parentale (RQAP).'
WHERE jurisdiction = 'QC' AND topic = 'leaves';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Québec — Heures supplémentaires : semaine de 40 heures, temps et demi',
  content_fr = 'En vertu de la Loi sur les normes du travail du Québec, les heures supplémentaires sont calculées en fonction de la semaine normale de travail de 40 heures pour la plupart des travailleurs. Les heures travaillées au-delà de 40 par semaine sont des heures supplémentaires, même si la semaine habituelle de l''entreprise est inférieure à 40 heures. Les heures supplémentaires doivent être payées à temps et demi — majorées de 50 % du taux horaire régulier (multiplier le taux horaire habituel par 1,5). Les primes ajoutées au taux horaire, comme les primes de soir ou de nuit, ne sont pas incluses dans le calcul des heures supplémentaires. Les heures comprises dans les vacances annuelles et les jours fériés légaux comptent comme des heures travaillées pour le calcul des heures supplémentaires. À la demande du travailleur, ou en vertu d''une convention collective ou d''un décret, les heures supplémentaires peuvent être remplacées par un congé payé à temps et demi au lieu d''un paiement. Certaines catégories de travailleurs, comme les ouvriers agricoles, n''ont pas droit à la prime de temps supplémentaire. Dans certaines circonstances, un travailleur peut refuser d''effectuer des heures supplémentaires.'
WHERE jurisdiction = 'QC' AND topic = 'overtime';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Québec — Intervalles de paie et retenues sur salaire permises',
  content_fr = 'En vertu de la Loi sur les normes du travail du Québec, administrée par la CNESST, l''employeur a un mois pour payer le premier salaire d''une nouvelle embauche ; par la suite, les salaires doivent être payés à intervalles réguliers d''au plus 16 jours (ou d''un mois pour les cadres). Si le jour de paie tombe un jour férié, le salaire doit être payé le jour ouvrable précédent, sauf s''il est versé par virement bancaire. À chaque paie, l''employeur doit remettre au travailleur un bulletin de paye indiquant la période de paie, les heures travaillées et payées, les heures supplémentaires, les primes, le taux de salaire, le salaire brut, la nature et le montant de chaque retenue, et le salaire net. L''employeur ne peut effectuer une retenue sur le salaire que si elle est exigée par une loi, un règlement, une ordonnance du tribunal, une convention collective, un décret ou un régime de retraite complémentaire obligatoire ; toute autre retenue requiert le consentement écrit du travailleur précisant son objet, consentement qu''il peut révoquer en tout temps — sauf le consentement à un régime de retraite obligatoire ou d''assurance collective.'
WHERE jurisdiction = 'QC' AND topic = 'pay_deductions';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Québec : 8 jours fériés chômés et payés et règle de rémunération pour le travail un jour férié',
  content_fr = 'Les travailleurs du Québec ont droit à 8 jours fériés chômés et payés en vertu de la Loi sur les normes du travail et de la Loi sur la fête nationale : le 1er janvier (Jour de l''An) ; le Vendredi saint ou le Lundi de Pâques, au choix de l''employeur ; la Journée nationale des patriotes (le lundi précédant le 25 mai) ; le 24 juin (Saint-Jean-Baptiste, Fête nationale) ; le 1er juillet (Fête du Canada ; s''il tombe le 24 juin, le congé est reporté au 2 juillet) ; la Fête du Travail (premier lundi de septembre) ; l''Action de grâce (deuxième lundi d''octobre) ; le 25 décembre (Noël). Pour avoir droit à l''indemnité fériée, le travailleur ne doit pas s''être absenté sans l''autorisation de l''employeur ou sans motif valable le jour ouvrable précédant ou suivant le jour férié. S''il ne travaille pas un jour férié, il a droit à une indemnité égale au 1/20 du salaire gagné (heures supplémentaires exclues) au cours des quatre semaines complètes précédant le jour férié. S''il travaille un jour férié, l''employeur doit lui payer son salaire régulier plus l''indemnité fériée, ou, à sa demande, remplacer l''indemnité par un congé compensatoire pris dans les trois semaines précédant ou suivant le jour férié.'
WHERE jurisdiction = 'QC' AND topic = 'public_holidays';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Québec — Conservation des registres de paie par l''employeur',
  content_fr = 'En vertu du Règlement sur le système d''inscription ou sur la tenue d''un registre (adopté en vertu de la Loi sur les normes du travail), l''employeur doit tenir un système d''inscription ou un registre avec les mentions prescrites pour chaque employé et chaque période de paie, pendant une période de trois ans par année de registres. Par ailleurs, la Loi sur le Régime de retraite du Québec exige que les registres de paie soient conservés au moins quatre ans après l''année financière au cours de laquelle un employé a cessé son emploi, et le délai de prescription du Code civil du Québec justifie généralement de conserver les dossiers des employés ayant cessé leur emploi pendant au moins trois ans après la cessation comme mesure de précaution judiciaire.'
WHERE jurisdiction = 'QC' AND topic = 'records_retention';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Québec — Aucun droit distinct à une indemnité de départ',
  content_fr = 'La Loi sur les normes du travail du Québec ne prévoit pas de droit distinct à une indemnité de départ séparée de l''obligation d''avis. Lorsqu''un employeur met fin à l''emploi d''un employé sans lui donner l''avis de cessation d''emploi requis, l''employé a droit à une indemnité compensant l''avis manquant — calculée comme le salaire régulier pour la période d''avis manquante, heures supplémentaires exclues. Cette indemnité est fonctionnellement semblable à ce que d''autres provinces appellent un « salaire en guise d''avis », et constitue la seule obligation monétaire légale lors de la cessation au-delà des salaires, de l''indemnité de vacances et des prestations minimales applicables en vertu des normes du travail. La Loi garantit séparément une protection contre le congédiement sans une cause juste et suffisante pour les travailleurs ayant 2 ans et plus de service, tranchée par le Tribunal administratif du travail, qui peut ordonner la réintégration ou une indemnité — mais il s''agit d''un recours fondé sur une plainte, et non d''un paiement automatique.'
WHERE jurisdiction = 'QC' AND topic = 'severance';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Québec — Avis individuel de cessation d''emploi',
  content_fr = 'En vertu de la Loi sur les normes du travail du Québec (art. 82–84), administrée par la CNESST, l''employeur doit donner un avis de cessation d''emploi écrit lorsqu''un employé est licencié, congédié ou mis à pied plus de 6 mois. La période d''avis dépend du service continu : 3 mois à 1 an de service, 1 semaine ; 1 à 5 ans, 2 semaines ; 5 à 10 ans, 4 semaines ; 10 ans et plus, 8 semaines. Aucun avis n''est requis si l''employé a moins de 3 mois de service continu, a accompli la tâche pour laquelle il a été embauché, est titulaire d''un contrat à durée déterminée, a été licencié en raison d''un cas de force majeure, ou a commis une faute grave justifiant le congédiement immédiat. L''employeur qui ne donne pas l''avis requis doit payer une indemnité égale au salaire régulier que l''employé aurait gagné pendant la période d''avis manquante, heures supplémentaires exclues. La période de vacances annuelles ne peut être comptée dans la période d''avis, et les avantages sociaux doivent être maintenus durant celle-ci.'
WHERE jurisdiction = 'QC' AND topic = 'termination_notice';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Québec — Vacances annuelles : durée et indemnité de 4 %/6 %',
  content_fr = 'En vertu de la Loi sur les normes du travail du Québec (art. 66–77), le droit aux vacances annuelles est fondé sur le service continu à la fin de l''année de référence (généralement du 1er mai au 30 avril). Moins de 1 an de service continu : 1 jour de vacances par mois complet de service continu, jusqu''à un maximum de 2 semaines, avec une indemnité de vacances de 4 % du salaire brut gagné durant l''année de référence. De 1 an à 3 ans : 2 semaines consécutives et 4 % du salaire brut. 3 ans et plus : 3 semaines consécutives et 6 % du salaire brut. Le seuil pour 3 semaines et l''indemnité de 6 % est donc de 3 ans de service continu, et non de 5. L''indemnité doit être versée en un seul paiement avant le début des vacances ou avec la paie régulière couvrant la période de vacances. Un employé ayant droit à 2 semaines peut demander une troisième semaine supplémentaire sans salaire, que l''employeur doit accorder.'
WHERE jurisdiction = 'QC' AND topic = 'vacation';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Québec — Bases CNESST sur les accidents du travail : obligations de l''employeur et remplacement du revenu',
  content_fr = 'Au Québec, les accidents du travail et les maladies professionnelles sont couverts par la CNESST (Commission des normes, de l''équité, de la santé et de la sécurité du travail) en vertu de la Loi sur les accidents du travail et les maladies professionnelles (LATMP). Un travailleur blessé au travail doit aviser son employeur et consulter un médecin ; l''employeur doit ensuite déposer un avis de l''employeur auprès de la CNESST dans les 48 heures si le travailleur ne peut travailler au-delà du jour de l''accident, et doit lui payer son salaire pour le jour de l''accident ainsi que les 14 jours civils suivants à 90 % du salaire net pour chaque jour de travail prévu manqué. Après ces 14 jours, la CNESST verse une indemnité de remplacement du revenu (IRR) de 90 % du revenu net du travailleur jusqu''à ce qu''il puisse reprendre le travail ou jusqu''à ce qu''un préjudice permanent soit évalué. S''il reste une incapacité permanente, le travailleur peut recevoir une indemnité forfaitaire pour préjudice corporel et des services de réadaptation. L''avis de l''employeur doit être déposé même si le travailleur ne manque aucun jour au-delà du jour de l''accident.'
WHERE jurisdiction = 'QC' AND topic = 'workplace_injury_basics';

-- ===== FEDERAL (14 chunks) =====

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Obligation d''accommodement en vertu de la Loi canadienne sur les droits de la personne',
  content_fr = 'En vertu de la Loi canadienne sur les droits de la personne (LCDP), les employeurs sous réglementation fédérale — notamment les banques, les entreprises de télécommunications, les compagnies aériennes, les entreprises de transport interprovincial et la fonction publique fédérale — ne doivent pas exercer de discrimination envers leurs employés ou candidats à un emploi pour des motifs protégés. La Loi énumère 13 motifs de distinction illicite : la race, l''origine nationale ou ethnique, la couleur, la religion, l''âge, le sexe (y compris la grossesse et la maternité), l''orientation sexuelle, l''identité ou l''expression de genre, l''état matrimonial, la situation de famille, les caractéristiques génétiques, la déficience, et l''état de personne graciée ou dont le dossier a fait l''objet d''une suspension. Les employeurs ont l''obligation d''accommoder les personnes jusqu''au point de contrainte excessive, en tenant compte des considérations de santé, de sécurité et de coût. La Commission canadienne des droits de la personne reçoit les plaintes, peut les renvoyer au Tribunal canadien des droits de la personne, et publie des lignes directrices sur les obligations procédurales et substantielles d''accommodement de l''employeur.'
WHERE jurisdiction = 'FED' AND topic = 'accommodation_basics';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Fédéral — Congédiement déguisé et plaintes de congédiement injuste (Code canadien du travail)',
  content_fr = 'En vertu de la partie III (section XIV) du Code canadien du travail, une personne ayant terminé 12 mois consécutifs d''emploi continu chez un employeur sous réglementation fédérale et qui s''estime injustement congédiée peut déposer une plainte de congédiement injuste. L''arbitre peut interpréter la plainte comme un congédiement déguisé lorsque l''employeur n''a pas littéralement congédié le travailleur, mais a par exemple imposé une modification unilatérale et fondamentale d''une condition d''emploi, forçant ainsi le travailleur à démissionner. La plainte écrite doit être déposée auprès du Programme du travail dans les 90 jours suivant la date du congédiement. Si l''inspecteur du Programme du travail ne peut régler l''affaire, la plainte est renvoyée à un arbitre, qui peut ordonner la réintégration, une indemnisation pour perte de salaire, ou toute autre mesure équitable. Contrairement à de nombreux régimes provinciaux, il n''existe aucun montant minimal ni formule légale de dommages-intérêts — l''arbitre dispose d''un large pouvoir discrétionnaire en equity.'
WHERE jurisdiction = 'FED' AND topic = 'constructive_dismissal';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Durée du travail, pauses et périodes de repos (Code canadien du travail)',
  content_fr = 'En vertu de la partie III du Code canadien du travail, la durée normale du travail des employés sous réglementation fédérale est de 8 heures par jour et de 40 heures par semaine. Les employés ont droit à une pause non rémunérée d''au moins 30 minutes au cours de chaque période de 5 heures consécutives de travail. Ils ont également droit à une période de repos d''au moins 8 heures consécutives entre deux périodes de travail ou quarts de travail. Des horaires de travail modifiés peuvent être convenus par écrit, permettant l''établissement d''une moyenne des heures sur 2 semaines ou plus (jusqu''à la limite prévue par règlement), sous réserve du respect des conditions approuvées. La durée maximale du travail est de 48 heures par semaine, mais peut être dépassée lorsque le règlement le permet expressément ou dans des circonstances exceptionnelles et imprévisibles (urgence, prévention d''une entrave sérieuse aux activités). L''employeur doit informer les employés de leurs heures de travail prévues au moins 96 heures à l''avance, ou leur donner un préavis de 24 heures pour tout changement de quart.'
WHERE jurisdiction = 'FED' AND topic = 'hours_of_work';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Fédéral — Mise à pied temporaire et rappel au travail (Code canadien du travail)',
  content_fr = 'En vertu de la partie III du Code canadien du travail, la mise à pied temporaire d''un employé sous réglementation fédérale est limitée dans le temps; toute mise à pied excédant la durée permise devient un licenciement. Une mise à pied ne doit pas dépasser 12 mois consécutifs. Si la mise à pied dépasse trois mois consécutifs, l''employeur doit soit rappeler l''employé, soit fournir l''avis de licenciement collectif requis en vertu de la section IX. Le Code ne prescrit pas de procédure de rappel spécifique pour les mises à pied individuelles (non collectives) de moins de trois mois, mais il exige que l''employeur respecte toute clause de rappel prévue dans le contrat de travail ou la convention collective. Un travailleur mis à pied demeure en relation d''emploi avec l''employeur pendant la durée de la mise à pied et conserve son ancienneté ainsi que ses droits d''accumulation d''avantages sociaux, sauf entente contraire.'
WHERE jurisdiction = 'FED' AND topic = 'layoffs_recall';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Congés prévus par le Code canadien du travail (employeurs sous réglementation fédérale)',
  content_fr = 'En vertu de la partie III du Code canadien du travail, les employés sous réglementation fédérale ont droit à de nombreux congés non rémunérés protégés par la loi. Congé personnel : jusqu''à 5 jours par année, dont les 3 premiers jours sont rémunérés après 3 mois consécutifs d''emploi continu. Congé de maladie : jusqu''à 27 semaines. Congé de maternité : jusqu''à 17 semaines. Congé parental : jusqu''à 63 semaines (ou 71 semaines si le congé de maternité n''est pas pris). Congé de soignant : jusqu''à 28 semaines pour prendre soin d''un membre de la famille gravement malade et présentant un risque significatif de décès. Congé pour maladie grave : jusqu''à 37 semaines pour un enfant gravement malade, 17 semaines pour un adulte de la famille gravement malade. Congé de décès : jusqu''à 10 jours par année, dont les 3 premiers sont rémunérés après 3 mois de service. Congé lié au décès ou à la disparition d''un enfant : jusqu''à 104 semaines (décès) ou 52 semaines (disparition). Congé pour violence familiale : jusqu''à 10 jours (5 rémunérés après 3 mois de service). Congé pour fonctions judiciaires ou de juré : selon les besoins. Congé pour pratiques traditionnelles autochtones : jusqu''à 5 jours par année (non rémunéré). Les employés doivent respecter les exigences prescrites en matière de préavis et de justification.'
WHERE jurisdiction = 'FED' AND topic = 'leaves';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Salaire minimum fédéral — employeurs sous réglementation fédérale',
  content_fr = 'Le salaire minimum fédéral, qui s''applique aux travailleurs des secteurs privés sous réglementation fédérale (services bancaires, télécommunications, transport interprovincial et international, services postaux, etc.), est fixé par règlement pris en vertu du Code canadien du travail et ajusté chaque année le 1er avril en fonction de l''indice des prix à la consommation. Depuis le 1er avril 2025, le salaire minimum fédéral est de 17,75 $ l''heure. Le taux fédéral s''applique à moins que le salaire minimum général des adultes dans la province ou le territoire où l''employé travaille habituellement ne soit plus élevé, auquel cas le taux provincial ou territorial supérieur s''applique.'
WHERE jurisdiction = 'FED' AND topic = 'minimum_wage';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Durée du travail et heures supplémentaires — employeurs sous réglementation fédérale (Code canadien du travail)',
  content_fr = 'En vertu de la partie III du Code canadien du travail, les heures supplémentaires des employés sous réglementation fédérale correspondent au temps travaillé au-delà de 8 heures par jour ou de 40 heures par semaine (durée normale de travail), selon le premier seuil atteint. Les heures supplémentaires doivent être rémunérées à un taux d''au moins 1,5 fois le taux de salaire régulier de l''employé. Avec l''accord écrit de l''employé, ou en vertu d''une convention collective, les heures supplémentaires peuvent être accumulées et prises sous forme de congé payé à raison de 1,5 heure de congé pour chaque heure supplémentaire travaillée. Des horaires de travail modifiés — autorisés par écrit — peuvent permettre l''établissement d''une moyenne des heures sur 2 semaines ou plus, les heures supplémentaires s''appliquant alors aux heures dépassant la moyenne normale établie. Certaines catégories d''employés sont exemptées des dispositions sur les heures supplémentaires par règlement (par exemple les cadres et certains professionnels). La durée maximale du travail est de 48 heures par semaine, sauf exceptions prévues par règlement ou en cas d''urgence.'
WHERE jurisdiction = 'FED' AND topic = 'overtime';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Fédéral — Retenues salariales permises et recouvrement de salaire (Code canadien du travail)',
  content_fr = 'En vertu de la partie III du Code canadien du travail (section VII — Salaire), un employeur ne peut effectuer de retenues sur le salaire d''un employé, sauf lorsqu''une loi fédérale ou provinciale, une ordonnance judiciaire, ou une autorisation écrite de l''employé l''exige ou le permet. L''autorisation écrite de l''employé pour une retenue doit préciser l''objet et le montant de celle-ci, et l''employé peut retirer son autorisation par écrit à tout moment pour les périodes de paie futures. L''employeur doit verser le salaire au plus tard à la date de paie régulière de la période de paie au cours de laquelle le travail a été effectué, et doit fournir un talon de paie indiquant le salaire brut, l''objet et le montant de chaque retenue, ainsi que le salaire net. À la cessation d''emploi, tous les salaires gagnés — y compris l''indemnité de vacances — deviennent exigibles au plus tard 30 jours après la date de cessation d''emploi, ou à la date de paie régulière, selon la première échéance. Le chef de la conformité et de l''application peut ordonner le versement d''une somme pour salaire impayé et peut la recouvrer comme créance civile.'
WHERE jurisdiction = 'FED' AND topic = 'pay_deductions';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Jours fériés fédéraux et indemnité de jour férié (Code canadien du travail)',
  content_fr = 'En vertu de la partie III (section V) du Code canadien du travail, les employés sous réglementation fédérale ont droit à 10 jours fériés payés par année : le jour de l''An, le Vendredi saint, le lundi de Pâques, la fête de Victoria, la fête du Canada, la fête du Travail, la Journée nationale de la vérité et de la réconciliation (30 septembre), l''Action de grâce, le jour du Souvenir et le jour de Noël. Pour être admissible à l''indemnité de jour férié, l''employé doit avoir accumulé au moins 30 jours d''emploi chez l''employeur. L''indemnité pour un jour férié non travaillé correspond à au moins 1/20 du salaire (à l''exclusion des heures supplémentaires) gagné au cours des quatre semaines précédant immédiatement la semaine du jour férié. L''employé qui travaille un jour férié a droit à au moins 1,5 fois son taux de salaire régulier pour les heures travaillées, en plus d''un jour férié de remplacement payé à une date ultérieure, ou du salaire régulier pour les heures travaillées en plus de l''indemnité de jour férié (1/20). Les employés peuvent convenir de substituer un autre jour à un jour férié, lequel devient alors leur jour férié à toutes fins prévues par le Code.'
WHERE jurisdiction = 'FED' AND topic = 'public_holidays';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Fédéral — Conservation des registres de paie et d''emploi par l''employeur (Code canadien du travail)',
  content_fr = 'En vertu de la partie III du Code canadien du travail (section XV.2 — Sanctions administratives pécuniaires, et le Règlement du Canada sur les normes du travail), un employeur sous réglementation fédérale doit tenir des registres précis pour chaque employé, notamment les heures travaillées chaque jour, les salaires versés, les heures supplémentaires, les congés annuels et l''indemnité de vacances, ainsi que toute retenue. Les registres doivent être conservés sous une forme permettant leur consultation ou leur reproduction, et doivent être conservés pendant au moins 36 mois (3 ans) après l''exécution du travail auquel ils se rapportent. Le chef de la conformité et de l''application ou un inspecteur peut exiger que l''employeur produise ces registres à tout moment. Le défaut de tenir ou de produire les registres exigés peut entraîner une sanction administrative pécuniaire.'
WHERE jurisdiction = 'FED' AND topic = 'records_retention';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Indemnité de départ — employeurs sous réglementation fédérale (Code canadien du travail)',
  content_fr = 'En vertu de la partie III (section X) du Code canadien du travail, l''indemnité de départ s''applique aux employés ayant terminé au moins 12 mois consécutifs d''emploi continu chez un employeur sous réglementation fédérale et dont l''emploi prend fin (licenciement individuel ou collectif). L''indemnité de départ correspond au plus élevé des deux montants suivants : deux jours de salaire régulier pour chaque année complète de service; ou cinq jours de salaire régulier. Il n''existe aucun plafond légal, de sorte que les employés de longue durée accumulent des droits proportionnellement plus élevés. L''indemnité de départ est distincte de l''avis de cessation d''emploi ou de l''indemnité en tenant lieu exigés en vertu de la section IX, et s''y ajoute. Elle ne s''applique pas lorsque l''employé a été congédié pour motif valable ou a refusé une offre raisonnable d''emploi de remplacement de l''employeur.'
WHERE jurisdiction = 'FED' AND topic = 'severance';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Préavis individuel de cessation d''emploi — employeurs sous réglementation fédérale (Code canadien du travail, partie III)',
  content_fr = 'En vertu de la partie III (section IX) du Code canadien du travail, l''employeur sous réglementation fédérale qui met fin à l''emploi d''un employé ayant terminé au moins 3 mois consécutifs d''emploi continu doit lui donner un préavis écrit d''au moins 2 semaines, ou une indemnité en tenant lieu équivalant à 2 semaines de salaire régulier. Lorsqu''un licenciement collectif est prévu (50 employés ou plus au cours d''une période de 4 semaines dans un même établissement industriel), l''employeur doit donner un avis écrit au ministre du Travail au moins 16 semaines à l''avance et collaborer à la mise en place d''un comité mixte de planification. Le préavis individuel est distinct de l''indemnité de départ prévue à la section X. Un employeur ne peut donner un préavis à un employé qui est en congé, notamment un congé de maladie, un congé de maternité ou tout autre congé prévu par la loi.'
WHERE jurisdiction = 'FED' AND topic = 'termination_notice';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Vacances annuelles — employeurs sous réglementation fédérale (Code canadien du travail)',
  content_fr = 'En vertu de la partie III (section IV) du Code canadien du travail, les employés sous réglementation fédérale acquièrent des droits à des vacances annuelles fondés sur leurs années de service chez le même employeur. Après 1 année d''emploi complétée : au moins 2 semaines de vacances et une indemnité de vacances d''au moins 4 % du salaire brut gagné au cours de l''année d''emploi complétée. Après 5 années consécutives : au moins 3 semaines de vacances et une indemnité de 6 %. Après 10 années consécutives : au moins 4 semaines de vacances et une indemnité de 8 %. Les vacances doivent être prises dans les 10 mois suivant la fin de l''année d''emploi complétée, en une seule période continue, à moins que l''employé n''en fasse la demande écrite contraire ou qu''une convention collective ne permette le fractionnement. L''indemnité de vacances est exigible au moins un jour avant le début des vacances. Le droit aux vacances continue de s''accumuler pendant les congés prévus par la loi.'
WHERE jurisdiction = 'FED' AND topic = 'vacation';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Fédéral — Absence d''un régime fédéral distinct d''indemnisation des accidents du travail pour les employés du secteur privé',
  content_fr = 'Il n''existe aucune commission fédérale unique des accidents du travail. Les employés du secteur privé travaillant pour des employeurs sous réglementation fédérale (banques, télécommunications, transport interprovincial, etc.) sont couverts par la loi sur les accidents du travail de la province où ils travaillent habituellement; ils déposent leurs demandes auprès de la commission provinciale compétente (par exemple la WSIB en Ontario ou la CNESST au Québec). La Loi sur l''indemnisation des agents de l''État accorde une couverture aux employés de la Couronne fédérale et à certaines autres catégories de travailleurs fédéraux, par l''intermédiaire de ces mêmes commissions provinciales, le gouvernement fédéral agissant comme employeur réputé. Les obligations de l''employeur en matière de retour au travail prévues à la partie III du Code canadien du travail s''appliquent peu importe la commission provinciale saisie de la demande : un employeur ne doit pas congédier, suspendre, mettre à pied ou rétrograder un employé en raison d''une absence causée par une maladie ou une blessure liée au travail, et doit, dans la mesure où cela est raisonnablement possible, réintégrer l''employé dans le même poste ou un poste comparable lorsqu''il est en mesure de reprendre le travail.'
WHERE jurisdiction = 'FED' AND topic = 'workplace_injury_basics';

-- ===== ONTARIO (13 chunks — minimum_wage already done in 0029) =====

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Code des droits de la personne de l''Ontario et obligation d''accommodement',
  content_fr = 'En vertu du Code des droits de la personne de l''Ontario, toute personne a droit à un traitement égal en matière d''emploi sans discrimination fondée sur les motifs protégés par le Code : la race, l''ascendance, le lieu d''origine, la couleur, l''origine ethnique, la citoyenneté, la croyance (religion), le sexe (y compris la grossesse et l''allaitement), l''orientation sexuelle, l''identité de genre, l''expression de genre, l''âge, l''existence d''un casier judiciaire, l''état matrimonial, l''état familial et le handicap. Les employeurs ont l''obligation d''accommoder jusqu''au point de contrainte excessive, en ne tenant compte que du coût, des sources externes de financement le cas échéant, et des exigences en matière de santé et de sécurité. La Commission ontarienne des droits de la personne (CODP) et le Tribunal des droits de la personne de l''Ontario (TDPO) administrent le système : les particuliers déposent leurs requêtes directement auprès du Tribunal, et la Commission intervient dans les affaires d''intérêt public et publie des directives.'
WHERE jurisdiction = 'ON' AND topic = 'accommodation_basics';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Ontario — Congédiement déguisé en vertu de la LNE',
  content_fr = 'En vertu de la LNE de l''Ontario, l''emploi d''une personne est réputé avoir pris fin si l''employeur la congédie de façon déguisée et que l''employé démissionne en réponse dans un délai raisonnable. Un congédiement déguisé peut survenir lorsqu''un employeur apporte une modification importante à une condition fondamentale d''emploi sans le consentement de l''employé — une réduction salariale importante, ou un changement négatif significatif au lieu de travail, aux heures, à l''autorité ou au poste — ou harcèle ou maltraite un employé, ou lui lance un ultimatum « démissionner ou être congédié ». Même une mise à pied « temporaire » au sens de la LNE peut constituer un congédiement déguisé si le contrat ne permet pas la mise à pied. Le guide de l''Ontario qualifie cette question de « complexe et difficile ».'
WHERE jurisdiction = 'ON' AND topic = 'constructive_dismissal';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Ontario : durée du travail, périodes de repos et périodes de repas',
  content_fr = 'En vertu de la Loi de 2000 sur les normes d''emploi de l''Ontario, la plupart des employés ne doivent pas travailler plus de 8 heures par jour ou 48 heures par semaine, sauf si l''employé et l''employeur en conviennent par écrit ou par voie électronique, et que toute limite quotidienne supérieure à 8 heures est précisée. Les employés ont droit à 11 heures consécutives de repos chaque jour, à 8 heures entre les quarts de travail (sauf si les deux quarts ne totalisent pas plus de 13 heures), et à au moins 24 heures consécutives de repos chaque semaine de travail ou 48 heures consécutives toutes les deux semaines. Une période de repas de 30 minutes doit être accordée après au plus 5 heures consécutives de travail — non rémunérée sauf si le contrat de travail le prévoit; l''employeur peut la fractionner en deux périodes avec l''accord de l''employé. Les dispositions sur les repos et les repas sont impératives, mais les limites d''heures de travail peuvent être dépassées par entente écrite ou électronique.'
WHERE jurisdiction = 'ON' AND topic = 'hours_of_work';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Ontario — Mise à pied temporaire et règles de rappel',
  content_fr = 'En vertu de la LNE de l''Ontario, un employé est en mise à pied temporaire lorsqu''un employeur réduit ou arrête son travail sans mettre fin au lien d''emploi; aucun avis écrit ou motif n''est requis sauf si un contrat ou une convention collective le prévoit. La mise à pied reste « temporaire » si elle dure : au plus 13 semaines dans toute période de 20 semaines consécutives; ou plus de 13 mais moins de 35 semaines dans toute période de 52 semaines consécutives sous conditions admissibles (paiements substantiels continus, cotisations aux avantages sociaux, ou date de rappel approuvée/convenue); ou, pour les employés syndiqués, 35 semaines et plus avec rappel prévu à la convention. Depuis le 27 novembre 2025, une mise à pied temporaire prolongée pouvant aller jusqu''à 52 semaines dans 78 semaines consécutives est possible par entente écrite, sous réserve de l''approbation du directeur des normes d''emploi. Toute mise à pied dépassant ces limites est réputée être un licenciement.'
WHERE jurisdiction = 'ON' AND topic = 'layoffs_recall';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Congés légaux protégés de la LNE de l''Ontario',
  content_fr = 'En vertu de la LNE de 2000 de l''Ontario, les employés ont droit à plusieurs congés non rémunérés protégés : congé de grossesse (jusqu''à 17 semaines), congé parental (jusqu''à 61 ou 63 semaines), congé d''urgence personnelle (3 jours de maladie + 3 jours de responsabilités familiales + 2 jours de deuil = 8 jours au total par année), congé familial pour aidants naturels (jusqu''à 8 semaines par membre de la famille visé), congé familial pour raison médicale (jusqu''à 28 semaines pour soigner une personne gravement malade présentant un risque significatif de décès), congé pour maladie grave (jusqu''à 37 semaines pour un enfant gravement malade, 17 semaines pour un adulte gravement malade), congé en cas de décès d''un enfant (jusqu''à 104 semaines), congé en cas de disparition d''un enfant liée à un crime (jusqu''à 104 semaines), congé pour violence familiale ou sexuelle (jusqu''à 10 jours + 15 semaines ; les 5 premiers jours payés après 13 semaines d''emploi), congé de don d''organe (jusqu''à 13 semaines), et congé de réserviste (durée du déploiement). Les conditions d''admissibilité en matière d''ancienneté et les obligations de préavis varient selon le type de congé.'
WHERE jurisdiction = 'ON' AND topic = 'leaves';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Ontario — Seuil et taux des heures supplémentaires',
  content_fr = 'En vertu de la LNE de 2000 de l''Ontario, les heures supplémentaires commencent à 44 heures de travail par semaine ; chaque heure au-delà de 44 doit être payée à 1,5 fois le taux de salaire régulier de l''employé (temps et demi). Le seuil de 44 heures est le minimum légal — un contrat peut établir un seuil inférieur. La rémunération des heures supplémentaires peut être remplacée par un congé payé à raison de 1,5 heure pour chaque heure supplémentaire si l''employeur et l''employé en conviennent par écrit ou par voie électronique. Les ententes d''établissement de moyennes (approuvées par le directeur des normes d''emploi ou convenues dans une convention collective) peuvent répartir les heures sur plusieurs semaines, le seuil d''heures supplémentaires s''appliquant alors à la moyenne. Certains employés sont exemptés de la partie VIII (heures supplémentaires) — notamment les cadres, les superviseurs et des catégories professionnelles et autres énumérées dans le Règl. de l''Ont. 285/01.'
WHERE jurisdiction = 'ON' AND topic = 'overtime';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Ontario — Retenues salariales et relevés de paie',
  content_fr = 'En vertu de la Loi de 2000 sur les normes d''emploi de l''Ontario, un employeur ne peut effectuer de retenue sur le salaire d''un employé que lorsqu''une loi de l''Ontario ou du Canada l''exige (impôt sur le revenu, cotisations d''assurance-emploi, cotisations au Régime de pensions du Canada), qu''une ordonnance du tribunal l''autorise, ou que l''employé a donné une autorisation écrite précisant un montant spécifique ou une méthode de calcul — une autorisation verbale ou générale est insuffisante, et l''employé peut révoquer une autorisation écrite pour une retenue faite au profit d''un tiers. Les employeurs doivent payer tous les salaires gagnés au cours d''une période de paie, autre que l''indemnité de vacances en cours d''accumulation, au plus tard le jour de paie régulier, et doivent fournir un relevé de paie le jour de paie ou avant, indiquant la période de paie, le taux de salaire, le salaire brut et son mode de calcul, le montant et l''objet de chaque retenue, tout montant pour chambre ou pension, et le salaire net. À la cessation d''emploi, les salaires et l''indemnité de vacances en souffrance sont exigibles au plus tard sept jours après le dernier jour travaillé ou le prochain jour de paie régulier, selon la date la plus tardive.'
WHERE jurisdiction = 'ON' AND topic = 'pay_deductions';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Ontario : jours fériés et règles d''indemnité de jour férié',
  content_fr = 'La Loi de 2000 sur les normes d''emploi de l''Ontario désigne 9 jours fériés : le jour de l''An, le Jour de la famille (troisième lundi de février), le Vendredi saint, la fête de Victoria, la fête du Canada, la fête du Travail, l''Action de grâce, le jour de Noël et le lendemain de Noël (26 décembre). Un employé est admissible à l''indemnité de jour férié s''il a travaillé la totalité de son dernier jour de travail régulier prévu avant le jour férié et de son premier jour après, sauf motif raisonnable d''absence. L''indemnité fériée correspond au total du salaire régulier et de l''indemnité de vacances gagnés au cours des quatre semaines de travail précédant la semaine du jour férié, divisé par 20. Un employé qui travaille un jour férié a droit à une prime de salaire (1,5 × taux régulier) pour toutes les heures travaillées plus un jour de remplacement avec indemnité, ou au salaire régulier pour la journée plus l''indemnité fériée. Des ententes de substitution peuvent remplacer un jour férié par un autre jour de congé. Certaines catégories d''employés (activités continues, hôtellerie/restauration) sont assujetties à des règles particulières.'
WHERE jurisdiction = 'ON' AND topic = 'public_holidays';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Ontario — Conservation des dossiers par l''employeur et périodes de conservation',
  content_fr = 'En vertu de la Loi de 2000 sur les normes d''emploi de l''Ontario, les employeurs doivent consigner et conserver certaines informations pour chaque employé. Le nom, l''adresse et la date de début d''emploi doivent être conservés trois ans après que l''employé cesse de travailler pour l''employeur. Les dates, heures et nombre d''heures travaillées chaque jour et chaque semaine, les renseignements figurant sur chaque relevé de paie, ainsi que les copies des ententes d''heures supplémentaires ou d''établissement de moyennes doivent chacun être conservés trois ans après le jour de travail, la semaine ou le dernier jour d''application de l''entente concernés. Les dossiers de vacances doivent généralement être conservés cinq ans après leur création. La LNE ne prescrit pas de format de dossier, mais les registres doivent être facilement accessibles pour inspection par un agent des normes d''emploi, même lorsqu''un comptable ou un tiers les conserve pour le compte de l''employeur.'
WHERE jurisdiction = 'ON' AND topic = 'records_retention';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Ontario — Indemnité de départ : un droit distinct avec conditions d''admissibilité',
  content_fr = 'En vertu de la LNE de l''Ontario, l''indemnité de départ est un droit distinct du préavis de licenciement ou de l''indemnité tenant lieu de préavis. Un employé n''y est admissible que si : (a) il a au moins 5 ans d''emploi chez l''employeur, ET (b) soit l''employeur a une masse salariale d''au moins 2,5 millions de dollars (Ontario), soit l''indemnité fait partie d''une cessation permanente de tout ou partie de l''activité d''un établissement où 50 employés ou plus voient leur emploi prendre fin dans une période de 6 mois. Le montant est d''une semaine de salaire régulier par année de service complète, plus un montant au prorata pour les années partielles, jusqu''à un maximum de 26 semaines de salaire. L''indemnité est payable au plus tard 7 jours après la date de licenciement ou le prochain jour de paie régulier, selon la date la plus tardive, à moins que l''employé n''accepte par écrit des versements échelonnés.'
WHERE jurisdiction = 'ON' AND topic = 'severance';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Ontario — Préavis individuel de licenciement en vertu de la Loi de 2000 sur les normes d''emploi',
  content_fr = 'En vertu de la LNE de 2000 de l''Ontario, un employeur qui met fin à l''emploi d''un employé doit lui donner un préavis écrit ou une indemnité en tenant lieu (ou une combinaison) égale à : 1 semaine si employé de 3 mois à moins de 1 an ; 2 semaines si de 1 an à moins de 3 ans ; 3 semaines si de 3 à moins de 4 ans ; 4 semaines si de 4 à moins de 5 ans ; 5 semaines si de 5 à moins de 6 ans ; 6 semaines si de 6 à moins de 7 ans ; 7 semaines si de 7 à moins de 8 ans ; 8 semaines si 8 ans ou plus. Aucun préavis n''est requis pour les employés ayant moins de 3 mois d''emploi, les employés coupables d''inconduite volontaire, ou ceux qui refusent un autre emploi raisonnable. La période de préavis ne doit pas chevaucher des vacances ou un congé légal. Pendant la période de préavis, l''employeur doit continuer à verser le salaire régulier, maintenir les cotisations aux régimes d''avantages sociaux, et ne peut réduire le taux de salaire ou les heures de l''employé.'
WHERE jurisdiction = 'ON' AND topic = 'termination_notice';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Ontario — Vacances annuelles et indemnité de vacances',
  content_fr = 'En vertu de la LNE de 2000 de l''Ontario, un employé en poste depuis moins de 5 ans a droit à un minimum de 2 semaines de vacances après chaque année de référence de 12 mois, et à une indemnité de vacances d''au moins 4 % du salaire brut (indemnité de vacances exclue) gagné pendant cette période. Après 5 ans d''emploi chez le même employeur, les minimums passent à 3 semaines et 6 %. Les vacances doivent être programmées en semaines complètes sauf si l''employé en fait la demande écrite contraire; elles doivent être prises dans les 10 mois suivant la fin de l''année de référence, ou une date d''achèvement antérieure choisie par l''employeur (l''« année de référence alternative »). L''indemnité de vacances doit être versée en une somme forfaitaire avant le début des vacances, ou aux jours de paie réguliers pendant les vacances si l''employé y consent, ou (à la suite d''une entente écrite) à intervalles réguliers tout au long de l''année. L''indemnité de vacances accumulée est toujours due à la cessation d''emploi, peu importe l''ancienneté de l''employé.'
WHERE jurisdiction = 'ON' AND topic = 'vacation';

UPDATE public.advisor_guidance_chunks SET
  title_fr   = 'Ontario — Bases WSIB sur les accidents du travail : déclaration et prestations pour perte de gains',
  content_fr = 'Les accidents du travail en Ontario sont couverts par la WSIB (Commission de la sécurité professionnelle et de l''assurance contre les accidents du travail) en vertu de la Loi de 1997 sur la sécurité professionnelle et l''assurance contre les accidents du travail. L''employeur doit payer au travailleur blessé la totalité de son salaire pour le jour de l''accident. Si le travailleur a besoin de soins au-delà des premiers soins, s''il est absent, gagne moins que son salaire régulier, ou a besoin de travail modifié à un salaire inférieur au salaire régulier (ou au salaire régulier pendant plus de 7 jours civils), l''employeur doit signaler l''accident à la WSIB dans les 3 jours ouvrables et remettre au travailleur une copie de la déclaration. Les travailleurs qui subissent une perte de revenus peuvent recevoir une prestation pour perte de gains égale à 85 % de la moyenne nette de leurs gains (pour les accidents survenus le 1er janvier 1998 ou après), jusqu''à un maximum annuel, versée toutes les deux semaines et révisée annuellement pendant un maximum de six ans.'
WHERE jurisdiction = 'ON' AND topic = 'workplace_injury_basics';
